
install! 'cocoapods', :warn_for_unused_master_specs_repo => false
use_frameworks!
inhibit_all_warnings!

platform :ios, '9.0'

target 'APIService_Example' do
  pod 'CSAPIService', :path => '../'
  pod 'BetterCodable', '0.4.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # 消除编译警告
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end

    end
  end
end
